import { StyleSheet } from 'react-native';
import { COLORS } from '../baseStyles';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.CARD,
    borderRadius: 16,
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 12,
    width: 130,
    height: 240,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 2,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  imageContainer: {
    alignItems: 'center',
    marginBottom: 8,
  },
  bookImage: {
    width: 100,
    height: 145,
    borderRadius: 12,
    backgroundColor: COLORS.BG,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 1,
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  bookTitle: {
    fontSize: 14,
    fontFamily: 'Poppins-Bold',
    color: COLORS.TEXT,
    textAlign: 'center',
    marginBottom: 4,
    lineHeight: 18,
    minHeight: 36,
  },
  bookAuthor: {
    fontSize: 11,
    fontFamily: 'Poppins-Regular',
    color: COLORS.SUBT,
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 16,
    minHeight: 16,
  },
  rating: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F2F1FD',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'center',
  },
  star: {
    marginRight: 4,
  },
  ratingText: {
    fontSize: 11,
    color: COLORS.ACCENT,
    fontFamily: 'Poppins-SemiBold',
  },
});
