import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../baseStyles';

export const libraryStyles = StyleSheet.create({
  backgroundDecoration: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    backgroundColor: COLORS.ACCENT,
    opacity: 0.05,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  card: {
    marginBottom: 16,
    backgroundColor: COLORS.CARD,
    borderRadius: 20,
    padding: 20,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  lastCard: {
    marginBottom: Platform.OS === 'android' ? 80 : 16,
    backgroundColor: COLORS.CARD,
    borderRadius: 20,
    padding: 20,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  sectionHeader: {
    flexDirection: 'column',
    marginBottom: 20,
    gap: 16,
  },
  titleWrap: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontFamily: 'Poppins-Bold',
    color: COLORS.TEXT,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: COLORS.SUBT,
    fontFamily: 'Poppins-Regular',
    lineHeight: 20,
    marginTop: 6,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  chipPrimary: {
    backgroundColor: COLORS.ACCENT,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    shadowColor: COLORS.ACCENT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
    minWidth: 80,
  },
  chipPrimaryText: {
    color: '#fff',
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
    fontSize: 13,
  },
  chipLight: {
    backgroundColor: '#F2F1FD',
    borderWidth: 1,
    borderColor: '#E0DDFF',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    minWidth: 80,
  },
  chipLightText: {
    color: COLORS.ACCENT,
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
    fontSize: 13,
  },
  emptyReading: {
    gap: 16,
    alignItems: 'center',
    paddingVertical: 20,
  },
  ctaButton: {
    alignSelf: 'center',
    backgroundColor: COLORS.ACCENT,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
    shadowColor: COLORS.ACCENT,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  ctaButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
    fontSize: 15,
  },
  favList: {
    paddingVertical: 6,
    paddingLeft: 8,
    paddingRight: 8,
    gap: 8,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: COLORS.CARD,
    padding: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '75%',
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.TEXT,
    marginBottom: 16,
    fontFamily: 'Poppins-Bold',
  },
  modalClose: {
    alignSelf: 'center',
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#EEF2FF',
  },
  modalCloseText: {
    color: '#5A4FFF',
    fontWeight: '700',
  },
  pickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    gap: 16,
    borderRadius: 12,
    backgroundColor: '#FAFAFA',
    marginVertical: 2,
  },
  pickerCover: {
    width: 48,
    height: 72,
    borderRadius: 8,
    backgroundColor: '#E5E7EB',
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 1,
  },
  pickerTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.TEXT,
    fontFamily: 'Poppins-SemiBold',
    flex: 1,
  },
  pickerAuthor: {
    fontSize: 13,
    color: COLORS.SUBT,
    fontFamily: 'Poppins-Regular',
    marginTop: 2,
  },
  pickerAction: {
    fontSize: 13,
    color: COLORS.ACCENT,
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.BORDER,
    opacity: 0.8,
    marginVertical: 4,
  },
  modalBackdropCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    backgroundColor: COLORS.CARD,
    borderRadius: 20,
    padding: 24,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  modalPrimaryTiny: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: COLORS.ACCENT,
    shadowColor: COLORS.ACCENT,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  modalPrimaryText: {
    color: '#fff',
    fontWeight: '700',
    fontFamily: 'Poppins-Bold',
    fontSize: 14,
  },
  modalCloseTiny: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#F2F1FD',
    borderWidth: 1,
    borderColor: '#E0DDFF',
    marginRight: 8,
  },
  rowEnd: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 12,
    gap: 8,
  },
  input: {
    backgroundColor: '#F8F9FA',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.TEXT,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    fontFamily: 'Poppins-Regular',
  },
  inputLabel: {
    fontSize: 14,
    color: COLORS.SUBT,
    marginTop: 12,
    marginBottom: 8,
    fontFamily: 'Poppins-Medium',
  },
  orText: {
    textAlign: 'center',
    color: '#6B7280',
    marginVertical: 8,
  },
  emptyAchievements: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  achievementsPreview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    color: COLORS.TEXT_SECONDARY,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
});
