import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, TYPOGRAPHY } from '../baseStyles';

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BG,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.BG,
  },
  loadingText: {
    ...TYPOGRAPHY.body,
    marginTop: 16,
    color: COLORS.SUBT,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.BG,
    paddingHorizontal: 24,
  },
  errorText: {
    ...TYPOGRAPHY.body,
    color: COLORS.ERROR,
    textAlign: 'center',
    marginVertical: 16,
  },
  retryButton: {
    backgroundColor: COLORS.ACCENT,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryText: {
    ...TYPOGRAPHY.body,
    color: '#fff',
    fontFamily: 'Poppins-SemiBold',
  },
  header: {
    alignItems: 'center',
    padding: 24,
    backgroundColor: COLORS.CARD,
    marginBottom: 12,
    borderRadius: 20,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: COLORS.CARD,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  avatarEditButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: COLORS.ACCENT,
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: COLORS.CARD,
  },
  name: {
    ...TYPOGRAPHY.heading,
    marginBottom: 4,
    textAlign: 'center',
  },
  username: {
    ...TYPOGRAPHY.body,
    color: COLORS.SUBT,
    marginBottom: 8,
  },
  bio: {
    ...TYPOGRAPHY.caption,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  editProfileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(90, 79, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(90, 79, 255, 0.3)',
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    marginTop: 8,
    alignSelf: 'center',
    minWidth: 140,
    gap: 8,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  editProfileText: {
    ...TYPOGRAPHY.small,
    fontFamily: 'Poppins-SemiBold',
    color: COLORS.ACCENT,
    fontSize: 14,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statBox: {
    alignItems: 'center',
    flex: 1,
  },
  statNumber: {
    fontSize: 24,
    fontFamily: 'Poppins-Bold',
    color: COLORS.ACCENT,
    marginBottom: 4,
  },
  statLabel: {
    ...TYPOGRAPHY.small,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  infoText: {
    ...TYPOGRAPHY.caption,
    flex: 1,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.CARD,
    marginBottom: 24,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FEE2E2',
    gap: 8,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  logoutText: {
    ...TYPOGRAPHY.body,
    color: COLORS.ERROR,
    fontFamily: 'Poppins-SemiBold',
  },
  modalContainer: {
    flex: 1,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.CARD,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    ...TYPOGRAPHY.subheading,
    fontSize: 20,
  },
  formContainer: {
    marginBottom: 24,
  },
  inputContainer: {
    marginBottom: 20,
  },
  bioInput: {
    height: 80,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  actionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  actionContent: {
    flex: 1,
  },
  actionTitle: {
    ...TYPOGRAPHY.body,
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 2,
  },
  actionSubtitle: {
    ...TYPOGRAPHY.caption,
  },
  settingsContainer: {
    maxHeight: Dimensions.get('window').height * 0.6,
  },
  settingsSection: {
    marginBottom: 24,
  },
  settingsSectionTitle: {
    ...TYPOGRAPHY.subheading,
    fontSize: 18,
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  settingButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  settingContent: {
    flex: 1,
  },
  settingTitle: {
    ...TYPOGRAPHY.body,
    fontFamily: 'Poppins-SemiBold',
    marginBottom: 2,
  },
  settingSubtitle: {
    ...TYPOGRAPHY.caption,
  },
  deleteWarningContainer: {
    paddingVertical: 20,
  },
  warningIconContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  warningTitle: {
    ...TYPOGRAPHY.subheading,
    fontSize: 20,
    color: COLORS.ERROR,
    textAlign: 'center',
    marginBottom: 12,
  },
  warningText: {
    ...TYPOGRAPHY.body,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 22,
  },
  warningList: {
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  warningItem: {
    ...TYPOGRAPHY.caption,
    marginBottom: 8,
    lineHeight: 20,
  },
  confirmationText: {
    ...TYPOGRAPHY.caption,
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 20,
  },
  confirmationWord: {
    fontFamily: 'Poppins-Bold',
    color: COLORS.ERROR,
  },
  confirmationInput: {
    borderWidth: 2,
    borderColor: COLORS.BORDER,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    backgroundColor: COLORS.CARD,
    textAlign: 'center',
    marginBottom: 20,
  },
  deleteButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: COLORS.ERROR,
    alignItems: 'center',
  },
  deleteButtonDisabled: {
    opacity: 0.6,
  },
  deleteButtonText: {
    ...TYPOGRAPHY.body,
    fontFamily: 'Poppins-SemiBold',
    color: '#fff',
  },
  inputLabel: {
    fontSize: 14,
    color: COLORS.SUBT,
    marginBottom: 8,
    fontFamily: 'Poppins-Medium',
  },
  input: {
    backgroundColor: '#F8F9FA',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.TEXT,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    fontFamily: 'Poppins-Regular',
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#F2F1FD',
    borderWidth: 1,
    borderColor: '#E0DDFF',
    alignItems: 'center',
  },
  cancelButtonText: {
    ...TYPOGRAPHY.body,
    fontFamily: 'Poppins-SemiBold',
    color: COLORS.ACCENT,
  },
  saveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: COLORS.ACCENT,
    alignItems: 'center',
  },
  saveButtonText: {
    ...TYPOGRAPHY.body,
    fontFamily: 'Poppins-SemiBold',
    color: '#fff',
  },
});
