import { StyleSheet } from 'react-native';

const ACCENT = '#5A4FFF';
const BG = '#F7F6F3';
const CARD = '#FFFFFF';
const TEXT = '#1F2328';
const SUBT = '#6B7280';
const BORDER = '#EAE7E1';
const SHADOW = 'rgba(0,0,0,0.06)';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: BG },
  scroll: { padding: 16, paddingBottom: 32 },
  card: {
    backgroundColor: CARD,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    shadowColor: SHADOW,
    shadowOpacity: 1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },

  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  rowEnd: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },

  sectionTitle: { fontSize: 18, fontWeight: '700', color: TEXT },
  sectionLink: { fontSize: 14, color: ACCENT, fontWeight: '700' },
  emptyText: { color: SUBT, paddingVertical: 8 },

  chipPrimary: {
    backgroundColor: ACCENT,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  chipPrimaryText: { color: 'white', fontWeight: '700' },
  chipLight: {
    backgroundColor: '#F2F1FD',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  chipLightText: { color: ACCENT, fontWeight: '700' },
  chipPrimarySmall: {
    backgroundColor: ACCENT,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  chipLightSmall: {
    backgroundColor: '#F2F1FD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },

  storyList: { paddingVertical: 6, gap: 12 },
  storyWrap: { alignItems: 'center', width: 76 },
  storyImageWrap: {
    width: 64,
    height: 64,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: 'transparent',
    padding: 2,
    backgroundColor: '#fff',
  },
  storyActive: { borderColor: ACCENT },
  storyImage: { width: '100%', height: '100%', borderRadius: 32 },
  storyName: { marginTop: 6, fontSize: 12, color: TEXT },

  viewerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewerCard: {
    width: '90%',
    aspectRatio: 9 / 16,
    backgroundColor: '#000',
    borderRadius: 16,
    overflow: 'hidden',
  },
  viewerBars: { flexDirection: 'row', gap: 6, padding: 10 },
  viewerBar: { flex: 1, height: 3, backgroundColor: 'rgba(255,255,255,0.25)', borderRadius: 4 },
  viewerBarActive: { backgroundColor: '#fff' },
  viewerImage: { flex: 1, resizeMode: 'cover' },
  viewerCaption: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    color: '#fff',
    fontWeight: '700',
  },
  viewerNav: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, flexDirection: 'row' },
  viewerTap: { flex: 1 },
  viewerClose: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 999,
  },
  viewerCloseText: { color: '#fff', fontWeight: '700' },

  postCard: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
  },
  postHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  postAvatar: { width: 40, height: 40, borderRadius: 20, marginRight: 10, backgroundColor: '#EEE' },
  postUserName: { color: TEXT, fontWeight: '700' },
  postTime: { color: SUBT, fontSize: 12 },
  postDots: { color: SUBT, fontSize: 18, marginLeft: 10 },
  postText: { color: TEXT, lineHeight: 20, marginBottom: 10 },
  postBookWrap: {
    flexDirection: 'row',
    gap: 12,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 12,
    padding: 8,
    marginBottom: 8,
    backgroundColor: '#FAFAFF',
  },
  postBookCover: { width: 56, height: 80, borderRadius: 8, backgroundColor: '#EEE' },
  postBookInfo: { flex: 1, justifyContent: 'center' },
  postBookTitle: { color: TEXT, fontWeight: '700' },
  postBookAuthor: { color: SUBT, marginTop: 2 },
  postActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  actionBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#F6F5FF',
  },
  actionText: { color: ACCENT, fontWeight: '700' },

  suggestList: { paddingVertical: 6, gap: 10 },
  userChip: {
    minWidth: 200,
    maxWidth: 280,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 14,
    backgroundColor: CARD,
    marginRight: 10,
    flex: 1,
  },
  userChipAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#EEE' },
  userChipContent: { flex: 1, marginRight: 8 },
  userChipName: { color: TEXT, fontWeight: '700', fontSize: 14 },
  userChipBio: { color: SUBT, fontSize: 11, marginTop: 2 },
  userChipMeta: { color: SUBT, fontSize: 12, marginTop: 2 },
  
  userChipBtn: {
    backgroundColor: ACCENT,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 50,
    maxWidth: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userChipBtnText: { color: 'white', fontSize: 10, fontWeight: '600' },
  userChipBtnOutline: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: ACCENT,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 50,
    maxWidth: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userChipBtnOutlineText: { color: ACCENT, fontSize: 10, fontWeight: '600' },
  userChipBtnDisabled: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 50,
    maxWidth: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userChipBtnDisabledText: { color: '#9CA3AF', fontSize: 10, fontWeight: '600' },
  userChipBtnDemo: {
    backgroundColor: '#FEF3C7', // Light yellow background for demo
    borderWidth: 1,
    borderColor: '#F59E0B', // Orange border for demo
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 50,
    maxWidth: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userChipBtnDemoText: { 
    color: '#92400E', // Dark orange text for demo
    fontSize: 10, 
    fontWeight: '600' 
  },
  
  createTestUsersButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F1FD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  createTestUsersText: {
    color: ACCENT,
    fontSize: 12,
    fontWeight: '600',
  },

  clubList: { paddingVertical: 6, gap: 12 },
  clubCard: {
    width: 156,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: CARD,
    marginRight: 12,
  },
  clubCover: { width: '100%', height: 98, borderRadius: 10, backgroundColor: '#EEE' },
  clubName: { marginTop: 8, color: TEXT, fontWeight: '700' },
  clubMeta: { color: SUBT, fontSize: 12, marginBottom: 8 },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
  modalSheet: {
    backgroundColor: CARD,
    padding: 14,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    maxHeight: '80%',
  },

  modalBackdropCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalCardWide: { backgroundColor: CARD, borderRadius: 16, padding: 14, width: '100%' },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalHeaderInfo: {
    flex: 1,
  },
  modalUserAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: ACCENT,
    overflow: 'hidden',
  },
  modalAvatarImage: {
    width: '100%',
    height: '100%',
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: TEXT, marginBottom: 4 },
  modalSubtitle: { fontSize: 14, fontWeight: '700', color: TEXT, marginTop: 8, marginBottom: 6 },
  inputMultiline: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 12,
    padding: 10,
    backgroundColor: '#FFF',
  },

  attachList: { gap: 10 },
  attachItem: {
    width: 140,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: '#FAFAFF',
    marginRight: 10,
  },
  attachItemActive: { borderColor: ACCENT },
  attachCover: { width: '100%', height: 90, borderRadius: 8, backgroundColor: '#EEE' },
  attachTitle: { marginTop: 6, color: TEXT, fontWeight: '700' },
  attachAuthor: { color: SUBT, fontSize: 12 },

  modalCloseTiny: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#EFEFFF',
  },
  modalCloseText: { color: ACCENT, fontWeight: '700' },
  modalPrimaryTiny: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: ACCENT,
  },
  modalPrimaryTinyDisabled: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#B8B3FF',
  },
  modalPrimaryText: { color: 'white', fontWeight: '700' },

  commentItem: { flexDirection: 'row', gap: 10, alignItems: 'flex-start', paddingVertical: 6 },
  commentAvatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#EEE' },
  commentAvatarContainer: {
    marginRight: 10,
  },
  commentUser: { color: TEXT, fontWeight: '700' },
  commentText: { color: TEXT },
  commentInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10 },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#FFF',
  },

  // New professional styles
  header: {
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerInfo: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 28,
    fontFamily: 'Poppins-Bold',
    color: TEXT,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 16,
    fontFamily: 'Poppins-Regular',
    color: SUBT,
  },
  userAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: ACCENT,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },

  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },

  badge: {
    backgroundColor: ACCENT,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    minWidth: 24,
    alignItems: 'center',
  },
  badgeText: {
    color: '#fff',
    fontSize: 12,
    fontFamily: 'Poppins-Bold',
  },

  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 18,
    color: '#e63946',
    marginTop: 16,
    marginBottom: 24,
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ACCENT,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  retryText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
  },

  loadingContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: SUBT,
    fontFamily: 'Poppins-Regular',
  },

  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  createFirstButton: {
    marginTop: 16,
    backgroundColor: ACCENT,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
  },
  createFirstText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
  },

  activityActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  addActivityButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  addActivityText: {
    color: ACCENT,
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
  },
});
